export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLE_TITLE_CONTAINS = 'SET_ARTICLE_TITLE_CONTAINS';
export const SET_ARTICLE_TEXT_CONTAINS = 'SET_ARTICLE_TEXT_CONTAINS';
export const SET_ARTICLE_START = 'SET_ARTICLE_START';
export const SET_ARTICLE_LIMIT = 'SET_ARTICLE_LIMIT';
export const SET_ARTICLE_SORT = 'SET_ARTICLE_SORT';